AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - node_modules/**/*
  DisplayCopNames: true
  DisplayStyleGuide: true
  ExtraDetails: true

Rails:
  Enabled: true

require: rubocop-rspec

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Exclude:
    - bin/setup
    - bin/update
