version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: foreman start -f Procfile.dev
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
      - "3035:3035"
    depends_on:
      - db
